version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: paladinai-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    networks:
      - paladinai-network

networks:
  paladinai-network:
    driver: bridge

volumes:
  valkey_data:
    name: paladinai-valkey-data